### ISSUE TITLE
读取配置文件后无法依然无法启动

### ISSUE THREAD

**Issue by Orisland** [diyigemt/mirai-boot#6]
我又回来了=。=
错误如下

代码中只有最初的测试代码，且为1.0.4

`2021-05-29 19:32:42 I/mirai-boot-status: 
2021-05-29 19:32:43 I/mirai-boot-status: 开始读取配置文件
2021-05-29 19:32:43 I/mirai-boot-status: 配置文件读取成功
java.lang.ClassNotFoundException: /test2123123123123
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.diyigemt.miraiboot.autoconfig.GlobalLoader.findAndAddClassesInPackageByFile(GlobalLoader.java:159)
	at net.diyigemt.miraiboot.autoconfig.GlobalLoader.getClasses(GlobalLoader.java:69)
	at net.diyigemt.miraiboot.autoconfig.MiraiApplication.run(MiraiApplication.java:93)
	at test123123123132.main(test.java:11)
java.lang.ClassNotFoundException: /test123123123132
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.diyigemt.miraiboot.autoconfig.GlobalLoader.findAndAddClassesInPackageByFile(GlobalLoader.java:159)
	at net.diyigemt.miraiboot.autoconfig.GlobalLoader.getClasses(GlobalLoader.java:69)
	at net.diyigemt.miraiboot.autoconfig.MiraiApplication.run(MiraiApplication.java:93)
	at test123123123132.main(test.java:11)
Exception in thread "main" java.lang.NoClassDefFoundError: META-INF/versions/9/module-info is not a class because access_flag ACC_MODULE is set
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.diyigemt.miraiboot.autoconfig.GlobalLoader.getClasses(GlobalLoader.java:106)
	at net.diyigemt.miraiboot.autoconfig.MiraiApplication.run(MiraiApplication.java:93)
	at test123123123132.main(test.java:11)`

**Comment by Orisland** [comment]
补充问题，当我将测试代码段，其实也就是md里给的例子，剪切到代码源目录之后，重新运行了一次，出现新问题。配置文件消失，重新出现了另一个资源文件夹，与之前test目录下生成的文件同名。此后我执行clean后再次运行main方法，配置文件无法重新出现，虚空读取配置文件成功后出现上述同样错误无法修改。此时配置文件已完全消失，无法重新调出。

**Comment by diyigemt** [comment]
好家伙，应该是包名的问题，请提供一下目录结构
如果真的是包名的问题，可以调整目录结构为
/src/main/java/xxx/yyy/Main
/src/main/java/xxx/Main
之类的
如果使用/src/main/java/xxx/Main，xxx请不要使用net、com之类
如果使用/src/main/java/xxx/yyy/Main，对xxx没有限制，而xxx最好不要使用与依赖项同名的名称

**Comment by Orisland** [comment]
> 好家伙，应该是包名的问题，请提供一下目录结构
> 如果真的是包名的问题，可以调整目录结构为
> /src/main/java/xxx/yyy/Main
> /src/main/java/xxx/Main
> 之类的
> 如果使用/src/main/java/xxx/Main，xxx请不要使用net、com之类
> 如果使用/src/main/java/xxx/yyy/Main，对xxx没有限制，而xxx最好不要使用与依赖项同名的名称

结构如图，真的是新建了一个项目啥都没的那种。
https://z3.ax1x.com/2021/05/29/2Epy3F.png

**Comment by diyigemt** [comment]
没错就是包名的问题
也算是个bug，修1.0.4刚发现的那种
你可以使用我上面提供的方案临时解决

**Comment by Orisland** [comment]
那配置文件消失的问题如何解决啊。。。。它……没了。。

**Comment by Orisland** [comment]
> 没错就是包名的问题
> 也算是个bug，修1.0.4刚发现的那种
> 你可以使用我上面提供的方案临时解决

https://z3.ax1x.com/2021/05/29/2EiVUI.png
如图，配置文件，他……好像再也出不来了。。。

**Comment by diyigemt** [comment]
2333333这，我还真没遇到过23333，你把data和config删了试试，实在不行你可以自己创建一个
```yaml
miraiboot:
  bots:
    -
      account: 123 # qq号
      password:
        kind: PLAIN # 密码类型 目前仅支持PLAIN纯文本类型
        value: pwd # qq密码
      configuration:
        protocol: ANDROID_PHONE # qq登录协议 支持 ANDROID_PHONE ANDROID_PAD ANDROID_WATCH
        device: device.json # 设备信息文件名
    # 可以配置多个 在@EventFilter中修改bot字段可以指定不同的bot处理事件
    - account: 123 # qq号
      password:
        kind: PLAIN # 密码类型 目前仅支持PLAIN纯文本类型
        value: pwd # qq密码
      configuration:
        protocol: ANDROID_PHONE # qq登录协议 支持 ANDROID_PHONE ANDROID_PAD ANDROID_WATCH
        device: device.json # 设备信息文件名
  logger:
    network: false # 是否在控制台显示bot的网络信息
    eventStatus: true # 是否在控制台打印事件执行失败信息 暂时不起作用
    debug: false # 是否在控制台打印事件解析信息 暂时不起作用
  alias: # 指令别名 将会自动注册 配置方式为 指令全名:别名
  configs: # 全局配置 所有全局配置均可以主动从GlobalConfig类中拿到 具体请看注释
    DEFAULT_COMMAND_START: "" # 默认指令开头 当@EventHandler中没有指定start时使用改配置
    DEFAULT_EVENT_NET_TIMEOUT: 300000 # 默认的上下文监听超时时间 5分钟

```
